### ISSUE TITLE
14pm 16.4.1

### ISSUE THREAD

**Issue by congratulation888** [roothide/Dopamine2-roothide#29]
The latest version of the jailbreak, the first installation is very fast, but if you restart and jailbreak again, the success rate is particularly low, all stuck at the initialization environment. This situation did not occur in the previous update, on the 16.4.1 system.

**Comment by roothider** [comment]
use Filza to zip and load /var/mobile/Library/Logs/CrashReporter

**Comment by congratulation888** [comment]
When I updated all the patches, it is now better to reboot my phone for jailbreaking. Thank you
