### ISSUE TITLE
Request an update to the latest version of Dopamine 2.2

### ISSUE THREAD

**Issue by moxuan1121** [roothide/Dopamine2-roothide#6]

**Comment by Xuebi-design** [comment]
1

**Comment by roothider** [comment]
may take weeks

**Comment by Void48** [comment]
> may take weeks

Patiently waiting. 🙏🏻

**Comment by moxuan1121** [comment]
**_ Are you coming soon?_**

**Comment by moxuan1121** [comment]
> may take weeks

** Are you coming soon?**

**Comment by amaoagoua** [comment]
Again, update the Dopamine 2.2.2 version synchronously, because the background of this version is very good
